<a href="https://colab.research.google.com/github/chaki/colabs/blob/master/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic PyTorch commands on CoLab
4/2020 @chakify

# Tensor

In [0]:
import torch
a = torch.ones(3)
b = torch.zeros(4)
print(a)
print(b)

tensor([1., 1., 1.])
tensor([0., 0., 0., 0.])


In [0]:
a[1]

tensor(1.)

Tensors are stored as a one-dimensional array; it's up to the tensors to reference it properly.

In [0]:
points = torch.tensor([3.0, 4.0, 5.0, 7.0, 8.0, 9.0])
points

tensor([3., 4., 5., 7., 8., 9.])

In [0]:
points.shape

torch.Size([6])

In [0]:
points.storage()

 3.0
 4.0
 5.0
 7.0
 8.0
 9.0
[torch.FloatStorage of size 6]

In [0]:
points = torch.tensor([[3.0, 4.0], [5.0, 6.0], [7.0, 8.0]])
points.size()

torch.Size([3, 2])

In [0]:
points.shape

torch.Size([3, 2])

Stride: how to find col or row along the one-dimensional storage

In [0]:
points.stride()

(2, 1)

In [0]:
points.dtype

torch.float32

# Transpose

In [0]:
points_t = points.t()
points_t

tensor([[3., 5., 7.],
        [4., 6., 8.]])

In [0]:
points.shape

torch.Size([3, 2])

In [0]:
points_t.shape

torch.Size([2, 3])

The original and transpose share same storage (i.e., same one-dimensional array)

In [0]:
id(points.storage)

140121533341488

In [0]:
id(points_t.storage)

140121533341488

# Indexing


In [0]:
points

tensor([[3., 4.],
        [5., 6.],
        [7., 8.]])

In [0]:
points[1:]

tensor([[5., 6.],
        [7., 8.]])

In [0]:
points[0:1]

tensor([[3., 4.]])

In [0]:
points[:1]

tensor([[3., 4.]])

In [0]:
points[:2]

tensor([[3., 4.],
        [5., 6.]])

In [0]:
points[1:, 1:]

tensor([[6.],
        [8.]])

In [0]:
points[1:, 0:]

tensor([[5., 6.],
        [7., 8.]])

In [0]:
points[1:, 0]

tensor([5., 7.])

# NumPy


In [0]:
points_np = points.numpy()
points_np

NameError: ignored

In [0]:
points2 = torch.from_numpy(points_np)
points2

tensor([[3., 4.],
        [5., 6.],
        [7., 8.]])

# GPU


In [0]:
points_gpu = torch.tensor([[3.0, 4.0], [5.0, 6.0], [7.0, 8.0]], device='cuda')

In [0]:
points_gpu

tensor([[3., 4.],
        [5., 6.],
        [7., 8.]], device='cuda:0')

# CSV Data


Mount GDrive

In [6]:
import csv
import numpy as np

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


Read CSV file into NumPy

Move NumPy to Torch (FloatTensor)

In [9]:
#wine_path = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv"
wine_path = "/content/gdrive/My Drive/coding/colabs/winequality-white.csv"
wine_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";", skiprows=1)
wine_numpy
col_list = next(csv.reader(open(wine_path), delimiter=';'))

wine_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [13]:
import torch
wine = torch.from_numpy(wine_numpy)
wine.shape, wine.type()

(torch.Size([4898, 12]), 'torch.FloatTensor')